#! /usr/bin/env node

import inquirer from "inquirer";

const randomNumber = Math.floor(Math.random() * 6 + 1)
console.log("Welcome to number guesing game.")

const answers = await inquirer.prompt([
    {
        name: "userGuessedNumber",
        type: "number",
        message: "Please guess the number generated by the computer which is between 1 - 6: "
    }
])
if (answers.userGuessedNumber === randomNumber){
    console.log(`Congratulations you have guessed the number ${answers.userGuessedNumber}`)
}
else 
{console.log(`You cannot guess the number. Please try again.`)}